name: EndlessCrystal
version: '${project.version}'
main: me.aricius.endlesscrystal.EndlessCrystal
authors: [Aricius, Kaykka_]
softdepend: [PlaceholderAPI]
api-version: 1.19

commands:
  krystal:
    description: Crystal command
    usage: /krystal <param>
permissions:
  endlesscrystal.give:
    default: op
  endlesscrystal.giveall:
    default: op
  endlesscrystal.take:
    default: op
  endlesscrystal.look:
    default: op
  endlesscrystal.pay:
    default: op
  endlesscrystal.set:
    default: op
  endlesscrystal.reset:
    default: op
  endlesscrystal.me:
    default: op
  endlesscrystal.reload:
    default: op
